export const AGENDA_MODULE_OPTIONS = 'AGENDA_MODULE_OPTIONS';
export const AGENDA = 'AGENDA';
export const SEQUENCER_METADATA = 'SEQUENCER_METADATA';
export const JOB_SEQUENCE_METADATA = 'JOB_SEQUENCE_METADATA';
export const PARAM_ARGS_METADATA = 'PARAM_ARGS_METADATA';
