export enum EnvironmentConfigKeyEnum {
  ORM_HOST = 'ORM_HOST',
  ORM_PORT = 'ORM_PORT',
  ORM_USERNAME = 'ORM_USERNAME',
  ORM_PASSWORD = 'ORM_PASSWORD',
  ORM_DATABASE = 'ORM_DATABASE',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  MONGODB_HOST = 'MONGODB_HOST',
}
