export enum LawBranchEnum {
  ADMINISTRATIVE,
  CIVIL,
  LAND,
  CONSTITUTIONAL,
  TAX,
  FAMILY,
  CUSTOMS,
  LABOR,
  CRIMINAL,
  PENAL_ENFORCEMENT,
  FINANCIAL,
  ENVIRONMENTAL,
  CIVIL_PROCEDURAL,
  ADMINISTRATIVE_PROCEEDINGS,
  CRIMINAL_PROCEDURE,
  ENTREPRENEURIAL,
  ECONOMIC,

  ALL = ADMINISTRATIVE |
    CIVIL |
    LAND |
    CONSTITUTIONAL |
    TAX |
    FAMILY |
    CUSTOMS |
    LABOR |
    CRIMINAL |
    PENAL_ENFORCEMENT |
    FINANCIAL |
    ENVIRONMENTAL |
    CIVIL_PROCEDURAL |
    ADMINISTRATIVE_PROCEEDINGS |
    CRIMINAL_PROCEDURE |
    ENTREPRENEURIAL |
    ECONOMIC,
}
